### ISSUE TITLE
开启代理执行python3 quickstart.py system后出现如下错误

### ISSUE THREAD

**Issue by ry1655251598** [AI-Citizen/SolidGPT#54]
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

**Comment by wwwwww1020** [comment]
Hi ry1655251598

看起来像没有成功连接open ai， 可以尝试换一个open ai api key。并确定请求是否被防火墙屏蔽。

Thanks,
Austin
