### ISSUE TITLE
有關於工作分流

### ISSUE THREAD

**Issue by Ethanalgo** [AI-Citizen/SolidGPT#55]
SolidGPT可以監察我的notion 多個page的task然後自動代分配給不同的員工嗎? task由我不定期新增在notion

**Comment by wwwwww1020** [comment]
目前版本只能使用单一page，未来会支持多pages。 分配给不同员工，这里的员工是指LLM Agent还是人类员工呢？ 在多Pages支持上线后，不同Page分配给不同LLM Agent是可以做到的。我们v0.2版本将会在月底上线，届时会有相关feature更新。感谢联系我们。
