### ISSUE TITLE
onboard project阶段：上传代码文件后点击start时报错

### ISSUE THREAD

**Issue by yjwu-tw** [AI-Citizen/SolidGPT#69]
Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by wwwwww1020** [comment]
您好，感谢使用我们的产品。
请问是在public host上面出现的报错还是开源版本的报错？

可以尝试不上传报错相关文件来暂时跳过问题。
如果方便上传代码可以发到我们邮箱aict@ai-citi.com，我们复现问题进行debug

**Comment by yjwu-tw** [comment]
你好，我本地运行的开源版本最新代码。并不知道是哪个文件报错，而且我上传的都是python文件并不包含上述符号

**Comment by wwwwww1020** [comment]
如果换其他代码库也会有一样的问题吗？
您的项目规模大约是多大的？
请问系统是windows/mac os/Linux？
浏览器是Chrome内核吗（建议使用Chrome）。

**Comment by yjwu-tw** [comment]
换solidgpt的代码库也一样报错，macOS，chrome浏览器

**Comment by wwwwww1020** [comment]
收到我们会来复现，并在这里更新进展，感谢反馈

**Comment by wwwwww1020** [comment]
重新部署但是没能复现问题，您可以看下在运行sh StartServer.sh后，console 里面显示的后端服务运行的端口是否是http://0.0.0.0:8000， 我们前端默认后端服务端口是8000，若不是可以在前端手动调整端口

https://github.com/AI-Citizen/SolidGPT/blob/f2bf37148fbb6133891acf3ed1d135a86c769853/solidportal/panel/src/config/config.js#L2

<img width="886" alt="Screen Shot 2023-10-22 at 11 19 11 PM" src="https://github.com/AI-Citizen/SolidGPT/assets/39673228/c52e5504-db9b-4f54-a5dc-c1ef243711f4">

**Comment by yjwu-tw** [comment]
我docker部署的。但我发现跟你这个info不同的是我有OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k，会不会是这个问题

**Comment by alexgong14** [comment]
probably, 我看到有人有一样的问题：https://stackoverflow.com/questions/55016899/appengine-warning-openblas-warning-could-not-determine-the-l2-cache-size-on
可以做的尝试：
1. config vm with more RAM
2. 初次启动webapp的时候等一些时间

**Comment by yjwu-tw** [comment]
谢谢，估计是我这台电脑配置太低跑不动。我再试试你们建议的方法好了，感谢
