### ISSUE TITLE
{"detail":"Not Found"}

### ISSUE THREAD

**Issue by WizKid1968** [AI-Citizen/SolidGPT#72]
I get the following when I start the server: {"detail":"Not Found"}.

I am on a Mac M1. When I run the shell script I'm routed to http://0.0.0.0:8000/ where I receive {"detail":"Not Found"}.
I'm confused, what gives?

**Comment by snnahs1** [comment]
where do you add the code for open?

**Comment by alexgong14** [comment]
how do you start the server, by default it should be using localhost (127.0.0.1)

**Comment by alexgong14** [comment]
@WizKid1968 This is probably not an issue, are you able to access http://0.0.0.0:8000/docs?
if not, you may try setting the port to 127.0.0.1, which is localhost, in the shell script when starting uvicorn and try accessing http://127.0.0.1:8000/docs

You should be able to see something like this:
![image](https://github.com/AI-Citizen/SolidGPT/assets/71686001/206d1eed-829c-45d8-bf47-0cf044dc9d0a)

**Comment by WizKid1968** [comment]
> where do you add the code for open?

I'm not sure I understand your question, but I believe you are asking what IDE I am using. I'm using VS Code.

**Comment by WizKid1968** [comment]
> @WizKid1968 This is probably not an issue, are you able to access http://0.0.0.0:8000/docs? if not, you may try setting the port to 127.0.0.1, which is localhost, in the shell script when starting uvicorn and try accessing http://127.0.0.1:8000/docs
> 
> You should be able to see something like this: ![image](https://user-images.githubusercontent.com/71686001/277857386-206d1eed-829c-45d8-bf47-0cf044dc9d0a.png)

Hi, yes I can access  http://0.0.0.0:8000/docs and I see the example you provided. What do I do, next?

**Comment by colinlaoaa** [comment]
> > @WizKid1968 This is probably not an issue, are you able to access http://0.0.0.0:8000/docs? if not, you may try setting the port to 127.0.0.1, which is localhost, in the shell script when starting uvicorn and try accessing http://127.0.0.1:8000/docs
> > You should be able to see something like this: ![image](https://user-images.githubusercontent.com/71686001/277857386-206d1eed-829c-45d8-bf47-0cf044dc9d0a.png)
> 
> Hi, yes I can access http://0.0.0.0:8000/docs and I see the example you provided. What do I do, next?

I think you can setup the UI, the web page, those end points were utilized in the react web. 

[Start UI portal](https://github.com/AI-Citizen/SolidGPT#start-ui-portal)
You'll need to install npm, and we recommend using version 9.8.1 or higher.

# From the project root folder
cd solidportal/panel  
npm i && npm start

**Comment by Xinchunran** [comment]
> > > @WizKid1968 This is probably not an issue, are you able to access http://0.0.0.0:8000/docs? if not, you may try setting the port to 127.0.0.1, which is localhost, in the shell script when starting uvicorn and try accessing http://127.0.0.1:8000/docs
> > > You should be able to see something like this: ![image](https://user-images.githubusercontent.com/71686001/277857386-206d1eed-829c-45d8-bf47-0cf044dc9d0a.png)
> > 
> > 
> > Hi, yes I can access http://0.0.0.0:8000/docs and I see the example you provided. What do I do, next?
> 
> I think you can setup the UI, the web page, those end points were utilized in the react web.
> 
> [Start UI portal](https://github.com/AI-Citizen/SolidGPT#start-ui-portal) You'll need to install npm, and we recommend using version 9.8.1 or higher.
> 
> # From the project root folder
> cd solidportal/panel npm i && npm start

This works for me!

**Comment by wwwwww1020** [comment]
Just dig in with the team, looks like you don't install redos or don't run the redos correctly. Please make sure you install and run the redos before run sh StartServer.sh

If you are Mac OS
Please run to start service after you install it 

brew service start redis


We also working on add this part to our readme thanks for the feedback and let me know if it works for you

**Comment by wwwwww1020** [comment]
Version update, ticket close, feel free to reopen this ticket if the issue still there
