### ISSUE TITLE
Cant upload folder ?

### ISSUE THREAD

**Issue by nPokemon** [AI-Citizen/SolidGPT#73]
TypeError: Failed to fetch

**Comment by nPokemon** [comment]
ERROR:celery.backends.redis:Connection to Redis lost: Retry (0/20) now.
ERROR:celery.backends.redis:Connection to Redis lost: Retry (1/20) in 1.00 second.

**Comment by wwwwww1020** [comment]
Hi nPokemon, looks like your redis didn't start or running correctly. Could you verify if you install and start Redis service correctly. Thanks!

**Comment by fengyunzaidushi** [comment]
确实是redis没有安装

**Comment by Xinchunran** [comment]
You may have already resolved it. I encountered the same issue, and it was resolved by executing `brew install redis` followed by `brew services start redis`. After that, you can initiate the backend by running `sh StartServer.sh`. To complete the process, launch the UI. This was tested on Macos 14

**Comment by wwwwww1020** [comment]
New version update, no need redis anymore, ticket close
