### ISSUE TITLE
Unable to Initiate `chat` with Repository on Publicly Hosted Web Application

### ISSUE THREAD

**Issue by NeverBuggy** [AI-Citizen/SolidGPT#77]
I am encountering difficulty utilizing the recently released chat feature on your publicly hosted website. It seems there isn't a clear method to initiate this feature.

Could you kindly assist me or direct me towards the corresponding instructions or guides?

**Comment by wwwwww1020** [comment]
Yes in our public hosted web app it is still in v0.2.0 without chat ability, you can clone our repo and deploy the chat locally

**Comment by wwwwww1020** [comment]
v0.3.0 release, feel free to try our chat feature in VSCode Extension
https://marketplace.visualstudio.com/items?itemName=AICT.solidgpt
